find_package(GMP QUIET)
if  (GMP_FOUND)
else  (GMP_FOUND)
message(WARNING,"gmplib cmake scripts were not found on your system. Installation of  GMP version 6.3.0 or above could not be verified.")
#set(BUILD_SHARED_LIBS_save BUILD_SHARED_LIBS)
#set(BUILD_SHARED_LIBS 1)
#set(BUILD_SHARED_LIBS BUILD_SHARED_LIBS_save)
#unset(BUILD_SHARED_LIBS_save)
endif  (GMP_FOUND)
