set(BUILD_SHARED_LIBS_save BUILD_SHARED_LIBS)
set(BUILD_SHARED_LIBS 0)
set(BUILD_ITT_save BUILD_ITT)
set(BUILD_ITT 0)
set(BUILD_PERF_TESTS_save BUILD_PERF_TESTS)
set(BUILD_PERF_TESTS 0)
set(BUILD_TESTS_save BUILD_TESTS)
set(BUILD_TESTS 0)
set(BUILD_opencv_apps_save BUILD_opencv_apps)
set(BUILD_opencv_apps 0)
set(WITH_PROTOBUF_save WITH_PROTOBUF)
set(WITH_PROTOBUF 0)
set(WITH_QUIRC_save WITH_QUIRC)
set(WITH_QUIRC 1)
set(WITH_LAPACK_save WITH_LAPACK)
set(WITH_LAPACK 0)
set(WITH_CUDA_save WITH_CUDA)
set(WITH_CUDA 0)
set(BUILD_opencv_dnn_save BUILD_opencv_dnn)
set(BUILD_opencv_dnn 0)
set(WITH_IPP_save WITH_IPP)
set(WITH_IPP 0)
set(WITH_OPENEXR_save WITH_OPENEXR)
set(WITH_OPENEXR 0)
set(WITH_JPEG_save WITH_JPEG)
set(WITH_JPEG 0)
set(WITH_OPENJPEG_save WITH_OPENJPEG)
set(WITH_OPENJPEG 0)
set(WITH_TIFF_save WITH_TIFF)
set(WITH_TIFF 0)
set(WITH_FFMPEG_save WITH_FFMPEG)
set(WITH_FFMPEG 0)

#export Eigen3_DIR=dist/eigen
set(Eigen3_DIR_save Eigen3_DIR)
set(Eigen3_DIR dist/eigen)
add_subdirectory(src/opencv opencv)
set(Eigen3_DIR Eigen3_DIR_save)
unset(Eigen3_DIR_save)

set(WITH_FFMPEG WITH_FFMPEG_save)
unset(WITH_FFMPEG_save)
set(WITH_TIFF WITH_TIFF_save)
unset(WITH_TIFF_save)
set(WITH_OPENJPEG WITH_OPENJPEG_save)
unset(WITH_OPENJPEG_save)
set(WITH_JPEG WITH_JPEG_save)
unset(WITH_JPEG_save)
set(WITH_OPENEXR WITH_OPENEXR_save)
unset(WITH_OPENEXR_save)
set(WITH_IPP WITH_IPP_save)
unset(WITH_IPP_save)
set(BUILD_opencv_dnn BUILD_opencv_dnn_save)
unset(BUILD_opencv_dnn_save)
set(WITH_CUDA WITH_CUDA_save)
unset(WITH_CUDA_save)
set(WITH_LAPACK WITH_LAPACK_save)
unset(WITH_LAPACK_save)
set(WITH_QUIRC WITH_QUIRC_save)
unset(WITH_QUIRC_save)
set(WITH_PROTOBUF WITH_PROTOBUF_save)
unset(WITH_PROTOBUF_save)
set(BUILD_opencv_apps BUILD_opencv_apps_save)
unset(BUILD_opencv_apps_save)
set(BUILD_TESTS BUILD_TESTS_save)
unset(BUILD_TESTS_save)
set(BUILD_PERF_TESTS BUILD_PERF_TESTS_save)
unset(BUILD_PERF_TESTS_save)
set(BUILD_ITT BUILD_ITT_save)
unset(BUILD_ITT_save)
set(BUILD_SHARED_LIBS BUILD_SHARED_LIBS_save)
unset(BUILD_SHARED_LIBS_save)
